---

- hosts: webserv
  become: true
  tasks:
  - name: Agregar claves jenkins
    apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
  - name: Agregar paquete jenkins
    shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - name: instalar jenkins
    apt: name=jenkins state=present

  - name: Agregar Llave Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Agregar Repositorio Docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Instalar Docker
    apt: update_cache=yes name=docker-ce state=latest

  - name: Cambiar ubuntu al grupo docker
    remote_user: ubuntu
    user:
      name: "ubuntu"
      group: "docker"
      append: yes

  - name: Install docker-compose
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  